name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: cd to workspace and build
      run: cd Wechat_chatroom_helper_android && ls && chmod +x ./gradlew && ./gradlew assembleRelease
    - name: create zip
      run: zip -r out ./*
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: prerelease
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: true
        files: |
          out.zip
